# Generated by Django 3.0.5 on 2020-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jokes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jokes',
                'ordering': ['id'],
            },
        ),
    ]
